//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSales.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int ID { get; set; }
        public long Number { get; set; }
        public System.DateTime ValidTru { get; set; }
        public int CVV { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
